Add Exclude parameter to exclude files
markwragg/PowerShell-HashCopy pull request #8
Opened 2022-06-20 06:34 UTC by shayki5

Hi, 
Thank you for your module, it's really useful!
I'm came across a problem when I needed to copy files but to exclude one file, I saw there is no such option so I've added it.
I have tested it and it works for me :)

2023-06-27 20:51 UTC, shayki5 commented
@markwragg Can you take a look? 🙏

2023-06-27 21:35 UTC, markwragg commented
Hey sorry for a while I wasn't getting notifications from GitHub so missed some things. I'll look at this tomorrow.

2023-06-28 08:41 UTC, markwragg requested changes

2023-06-28 08:41 UTC, markwragg commented on HashCopy/Public/Copy-FileHash.ps1
> +        [string]
Make this input an array of strings i.e `[string[]]`

2023-06-28 08:41 UTC, markwragg commented on HashCopy/Public/Copy-FileHash.ps1
> -            $SourceFiles = (Get-ChildItem -Path $Source -Recurse:$Recurse -File).FullName
It looks like its valid for `-Exclude` to be passed `$null` so we can just always include it here and it negates the need for the rest of the additions.

2023-06-28 09:06 UTC, shayki5 commented on HashCopy/Public/Copy-FileHash.ps1
> -            $SourceFiles = (Get-ChildItem -Path $Source -Recurse:$Recurse -File).FullName
but we still need to convert to array, no?

2023-06-28 10:28 UTC, markwragg commented on HashCopy/Public/Copy-FileHash.ps1
> -            $SourceFiles = (Get-ChildItem -Path $Source -Recurse:$Recurse -File).FullName
No there's no need to convert it to an array, because we've made the input parameter an array.

2023-06-28 10:28 UTC, markwragg commented on Documentation/Copy-FileHash.md
> +The file list should be seperated with a comma. for example: `test1.txt,test2.txt`
Remove this line

2023-06-28 10:29 UTC, markwragg commented on Documentation/Copy-FileHash.md
> +Exclude files from be copied.
Reword to "Exclude one or more files from being copied".

2023-06-28 14:27 UTC, markwragg commented
Looks good to me, thank you for contribution!

2023-06-28 14:27 UTC, merged